# Generated by Django 2.0.5 on 2020-06-21 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('CPF', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('nome', models.CharField(max_length=200, null=True)),
                ('user_ativo', models.BooleanField(default=True)),
                ('user_adm', models.BooleanField(default=False)),
                ('especialidade', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqtle', models.IntegerField()),
                ('sqtld', models.IntegerField()),
                ('sqtl', models.IntegerField()),
                ('d_dez', models.IntegerField()),
                ('qtd_total_verticilos', models.IntegerField()),
                ('qtd_total_arcos', models.IntegerField()),
                ('qtd_total_presilhas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ImpressaoDigital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MaoDireita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_dedo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaoEsquerda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_dedo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(default='avatar.png', null=True, upload_to='pacientes')),
                ('nome_paciente', models.CharField(max_length=100)),
                ('cpf_paciente', models.CharField(max_length=12)),
                ('idade', models.IntegerField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Padrao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padroes', models.CharField(choices=[('W', 'Verticilo'), ('L', 'Presilha'), ('A', 'Arco')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Potencialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('F', 'Força'), ('V', 'Velocidade'), ('CM', 'Coordenação Motora'), ('A', 'Agilidade'), ('R', 'Resistência')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='maoesquerda',
            name='padrao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mao_esquerda', to='site_sicabio.Padrao'),
        ),
        migrations.AddField(
            model_name='maodireita',
            name='padrao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mao_direita', to='site_sicabio.Padrao'),
        ),
        migrations.AddField(
            model_name='impressaodigital',
            name='mao_direita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='im_digital', to='site_sicabio.MaoDireita'),
        ),
        migrations.AddField(
            model_name='impressaodigital',
            name='mao_esquerda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='im_digital', to='site_sicabio.MaoEsquerda'),
        ),
        migrations.AddField(
            model_name='impressaodigital',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='im_digital', to='site_sicabio.Paciente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='site_sicabio.Paciente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='id_profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analise',
            name='Resultado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analise', to='site_sicabio.Potencialidade'),
        ),
        migrations.AddField(
            model_name='analise',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='site_sicabio.Paciente'),
        ),
    ]
