# Generated by Django 2.0.5 on 2020-07-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dt_nascimento',
            field=models.DateField(blank=True,null=True),
        ),
    ]
