# Generated by Django 2.0.5 on 2020-07-01 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('site_sicabio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maodireita',
            name='padrao',
        ),
        migrations.RemoveField(
            model_name='maoesquerda',
            name='padrao',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='id_paciente',
            new_name='paciente',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='id_profissional',
            new_name='profissional',
        ),
        migrations.RenameField(
            model_name='profissional',
            old_name='user_ativo',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='profissional',
            old_name='user_adm',
            new_name='is_staff',
        ),
        migrations.RemoveField(
            model_name='impressaodigital',
            name='mao_direita',
        ),
        migrations.RemoveField(
            model_name='impressaodigital',
            name='mao_esquerda',
        ),
        migrations.AddField(
            model_name='impressaodigital',
            name='dedo',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='impressaodigital',
            name='mao',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='impressaodigital',
            name='padrao',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_sicabio.Padrao'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='profissional',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profissional',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='impressaodigital',
            name='img_path',
            field=models.ImageField(null=True, upload_to='impressoes'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf_paciente',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank='avatar.png', default='avatar.png', null=True, upload_to='pacientes'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='MaoDireita',
        ),
        migrations.DeleteModel(
            name='MaoEsquerda',
        ),
    ]
