# Generated by Django 2.0.5 on 2020-06-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0002_auto_20200530_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressaodigital',
            name='img_path',
            field=models.ImageField(upload_to=''),
        ),
    ]
