# Generated by Django 2.0.5 on 2020-06-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0002_auto_20200621_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
