# Generated by Django 2.0.5 on 2020-07-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0002_auto_20200701_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressaodigital',
            name='dedo',
            field=models.CharField(max_length=200),
        ),
    ]
