# Generated by Django 2.0.5 on 2020-06-07 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0003_auto_20200605_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='user_cpf',
            new_name='CPF',
        ),
    ]
