# Generated by Django 2.0.5 on 2020-06-24 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0003_profissional_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='paciente',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_sicabio.Paciente'),
        ),
    ]
