# Generated by Django 2.0.5 on 2020-06-24 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0004_profissional_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='paciente',
        ),
    ]
