# Generated by Django 2.0.5 on 2020-07-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0004_auto_20200719_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data',
            field=models.CharField(max_length=15),
        ),
    ]
