# Generated by Django 2.0.5 on 2020-07-01 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0004_auto_20200701_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impressaodigital',
            name='padrao',
        ),
    ]
