# Generated by Django 2.0.5 on 2020-06-10 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0005_profissional_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='user',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
