# Generated by Django 2.0.5 on 2020-06-24 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0005_remove_profissional_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='profissional',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
