# Generated by Django 2.0.5 on 2020-07-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0005_auto_20200719_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='horario',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dt_nascimento',
            field=models.CharField(max_length=15),
        ),
    ]
