# Generated by Django 2.0.5 on 2020-07-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0005_remove_impressaodigital_padrao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressaodigital',
            name='mao',
            field=models.CharField(max_length=200),
        ),
    ]
