# Generated by Django 2.0.5 on 2020-06-13 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0006_auto_20200610_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='imp_digital',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='imp_digital', to='site_sicabio.ImpressaoDigital'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='resultado_perfil',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='imp_digital', to='site_sicabio.Analise'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
