# Generated by Django 2.0.5 on 2020-07-03 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0006_auto_20200702_2010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImpressaoDigital',
            new_name='Impressao',
        ),
    ]
