# Generated by Django 2.0.5 on 2020-07-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0006_auto_20200719_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressao',
            name='img_path',
            field=models.ImageField(blank=True, null=True, upload_to='impressoes'),
        ),
    ]
