# Generated by Django 2.0.5 on 2020-06-26 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0007_auto_20200625_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressaodigital',
            name='img_path',
            field=models.ImageField(null=True, upload_to='impressoes'),
        ),
        migrations.AlterField(
            model_name='maoesquerda',
            name='padrao',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mao_esquerda', to='site_sicabio.Padrao'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='profissional',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
