# Generated by Django 2.0.5 on 2020-07-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0007_auto_20200702_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='dt_nascimento',
            field=models.CharField(max_length=8),
        ),
    ]
