# Generated by Django 2.0.5 on 2020-06-13 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0008_auto_20200612_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(default=True, null=True, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profissional',
            name='user',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
