# Generated by Django 2.0.5 on 2020-06-26 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0008_auto_20200625_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maodireita',
            name='padrao',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mao_direita', to='site_sicabio.Padrao'),
        ),
    ]
