# Generated by Django 2.0.5 on 2020-07-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0008_auto_20200722_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressao',
            name='img_path',
            field=models.ImageField(blank=True, default='media/avatar.png', null=True, upload_to='impressoes'),
        ),
    ]
