# Generated by Django 2.0.5 on 2020-06-26 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0009_auto_20200625_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dedos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedos', models.CharField(choices=[('P', 'Polegar'), ('I', 'Indicador'), ('ME', 'Médio'), ('A', 'Anular'), ('MI', 'Mínimo')], max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='maodireita',
            name='nome_dedo',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='mao_direita', to='site_sicabio.Dedos'),
        ),
        migrations.AlterField(
            model_name='maoesquerda',
            name='nome_dedo',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='mao_esquerda', to='site_sicabio.Dedos'),
        ),
    ]
