# Generated by Django 2.0.5 on 2020-07-22 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0009_auto_20200722_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impressao',
            old_name='img_path',
            new_name='img',
        ),
    ]
