# Generated by Django 2.0.5 on 2020-06-15 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0009_auto_20200612_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='imp_digital',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='resultado_perfil',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(null=True, upload_to='pacientes'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
