# Generated by Django 2.0.5 on 2020-06-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0010_auto_20200625_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank='avatar.png', default='avatar.png', null=True, upload_to='pacientes'),
        ),
    ]
