# Generated by Django 2.0.5 on 2020-06-16 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0010_auto_20200615_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='user',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
