# Generated by Django 2.0.5 on 2020-07-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0010_auto_20200722_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressao',
            name='mao',
            field=models.CharField(choices=[('ME', 'Mão Esquerda'), ('MD', 'Mão Direita')], max_length=2),
        ),
    ]
