# Generated by Django 2.2.14 on 2020-07-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0011_auto_20200722_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassword',
            name='confirmed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Confirmado?'),
        ),
    ]
