# Generated by Django 2.0.5 on 2020-06-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0011_auto_20200627_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='id_paciente',
            new_name='paciente',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='id_profissional',
            new_name='profissional',
        ),
        migrations.AlterField(
            model_name='profissional',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
