# Generated by Django 2.2.14 on 2020-07-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0012_auto_20200724_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf_paciente',
            field=models.CharField(max_length=12),
        ),
    ]
