# Generated by Django 2.0.5 on 2020-06-27 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0012_auto_20200627_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='paciente',
            new_name='paciente_id',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='profissional',
            new_name='profissional_id',
        ),
    ]
