# Generated by Django 2.2.14 on 2020-07-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sicabio', '0013_auto_20200724_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf_paciente',
            field=models.CharField(default=False, max_length=12, unique=True),
        ),
    ]
